---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - databases.example.com
  resources:
  - mongodbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - databases.example.com
  resources:
  - mongodbs/finalizers
  verbs:
  - update
- apiGroups:
  - databases.example.com
  resources:
  - mongodbs/status
  verbs:
  - get
  - patch
  - update
